"""The ids a `covers()` marker may name, and the AGENTS.md rule each one means.

The value is a distinctive phrase from the rule itself, so `rg "<phrase>"
AGENTS.md` lands on it. Keep it that way — a paraphrase makes the rule
unfindable from here, which is the only navigation this file offers.

Registering an id is how a rule enters the gap list — do it when you decide a
rule is worth guarding, not when you write the test.
"""

from __future__ import annotations

INVARIANTS: dict[str, str] = {
    # Docs, packaging and the console script.
    "docs.meta.never-do-not-lines-are-invariants": "Obey the **Never** / **Do not** lines — they encode paid-for",
    "docs.feature-guide-url.unpinned": "window. **Do not** pin it to a tag.",
    "docs.references.backticks-resolve": "**Repo-wide invariant tests**",
    "inventory.identity.never-stored": "a network round-trip). **Never** add a stored identity file.",
    "skills.no-redundant-gesture-skill": "**Do not** re-add a skill for a gesture the daemon",
    # TUI: table, header, footer, palette.
    "table.links.escape-reaches-terminal": "**The hover tooltip names the destination**",
    "table.status-slot.pad-even-when-blank": "🔇/🔔 differ in ink width per font; **do not** drop that padding.",
    "table.ticket-link.no-renderer-resolve": "**Do not** answer a missing link by resolving one in",
    "header.bar.countdowns-anchored-right": "`#header-repo` owns the one `1fr` slot",
    "header.repo-segment.no-repo-column-alternative": "**Do not** answer this with a Repo column (it duplicates the header row",
    "header.brand.url-as-argument": "**Do not** import the URL into the widget, and **do not** answer",
    "header.menu.label-not-the-key": "**Do not** move it into `FooterBar`, and **do not** print the key beside it.",
    "header.tick-glyphs.tooltip-spells-out-every-glyph": "**Do not** put a glyph in the bar that the tooltip doesn't spell out.",
    "header.feature-guide.no-local-path": "**never** point this at a local path",
    "header.announce-upgrade.no-version-check-widen": "**Do not** widen it into a version check, a `u` key, or a re-exec.",
    "palette.commands.order-is-the-menu": "`discover` yields in tuple order",
    "palette.config-commands.discover-hit-required": "**Do not** add a palette entry without a `discover` hit.",
    "globalkeys.sync-vs-output-separation": "**Do not** give `action_show_output` a key back",
    "footer.tooltips.single-widget-not-per-key": "**Do not** rebuild the footer as a widget per key.",
    "hidden.h.single-key-three-meanings": "**Do not** re-introduce a second key for reveal.",
    "tui.on-repo-done.daemon-only-cell-writes": "**Never** let it write a cell — only the daemon writes.",
    "tui.signals.no-signal-signal": "**Never** `signal.signal` — it raises off the main thread.",
    "tui.diff-key.not-reintroduced": "**Do not** re-add a row key that pipes into `cmux diff`",
    "tui.manual-nudge-key.not-reintroduced": "**Do not** re-add a manual nudge key with a canned message",
    "stdout.queue-writer.no-per-tick-redirect": "**never** per-tick `redirect_stdout` (the threads race).",
    "ask.line.no-comment-reattach": "**Do not** re-attach comments here.",
    # Row actions, bands and folds.
    "bands.snoozed.no-glyph-still-suppresses-bell": "**Snooze has no row glyph but still suppresses",
    "folds.snoozed-toggle.z-key-only": "**Do not** hang this off `h` or a new key.",
    "folds.review.never-persist-marker": '**Do not** persist a "this is a review" marker.',
    "folds.partial.keyed-on-completeness": "**Do not** re-key this on the bucket being empty rather than",
    "folds.trailing.pass-order-not-rank": "so **do not** reorder that tuple expecting names to sort it out",
    "folds.collapse.create-time-only": "**Do not** promote this to an unconditional re-assert",
    "folds.collapse.no-read-back": "and **do not** read `is_collapsed` back to",
    "folds.restore.create-only": "**It can only create**",
    "folds.restore.separate-read-functions": "**Do not** re-merge the two functions.",
    "folds.anchor.owns-a-live-shell": "**The anchor must own a live shell",
    "folds.mystery.not-closed": "**Do not** read this as having closed that question.",
    "rowaction.z-full-cycle.no-folds-under-only-repo": "**Do not** instead build `folds` under `only_repo`",
    "rowaction.z-full-cycle.no-move-to-fast-tick": "**Do not** move the pass to the fast tick, whose network-free",
    # Stacks.
    "stacks.derive.no-gh-view-no-persist": "**Do not** shell out to `gh stack view`, and **do not** persist a stack.",
    "stacks.group-header.tip-not-root": "**Do not** re-name the group after the root.",
    "stacks.anchor.durable-anchor-required": '**Do not** "simplify" this back to using the anchor `create` returns.',
    "stacks.snoozed-diversion.not-position-based": "— **do not** re-introduce a position-based answer",
    "stacks.tui-nesting.one-level-only": "— **do not** restore the per-level cascade.",
    # Cache keying and cell hygiene.
    "cache.key.flat-cells-by-worktree-path": "**Every flat cell is keyed by worktree path",
    "cache.renderer.never-reads-source-state": "**Never** let a renderer read source state directly.",
    "cache.strip-control.single-seam-in-read-text": "**Do not** re-implement it per renderer, and **do not** move it to",
    "cache.session-cells.daemon-never-writes": "**Do not** extend this exception to a new cell — the daemon must never *write* one.",
    "pr-list.one-per-head-branch": "### The live PR list carries at most one PR per head branch",
    "wt-cost.slug.one-way-only": "**Do not** try to recover a path from a slug.",
    "wt-cost.gate.data-not-plan": "**Do not** add a config field, and **do not** try to detect the plan.",
    "config.atomic-write.pid-scoped-suffix": "**Do not** go back to a fixed suffix",
    "config.atomic-write.no-reinline": (
        "**do not** re-inline the write at a `config.py` call site"
    ),
    # cmux events, pills and sidebar naming.
    "events.cursor-file.not-cache-cell": "**Do not** grow it into stored inventory or route it through",
    "events.doorbell.trigger-only": "**Do not** feed an event into a decision, a cell, or the slow tick.",
    "events.self-close.single-funnel": "the funnel every close path goes through; **do not** re-implement",
    "events.sidebar-x.routes-to-refuse-not-force": "**Do not** map the X onto `C`.",
    "pills.pr-pill.exclusive-renderer": "**Do not** re-enable any without turning the `pr` pill off",
    "pills.pr-pill.coverage-narrower-accepted": '**do not** "fix" it by spawning pills for untracked workspaces.',
    "pills.wip-suppression.not-reorder": "**Do not** answer a buried pill by reordering `KIND_ORDER`",
    "sidebar-tag.separator.last-char": "**A tag ending in a non-alphanumeric takes a space",
    "sidebar-tag.token.resolved-string-only": "teach `tag_workspace_name` about it; it takes a resolved string",
    "sidebar-tag.naming.two-sites-only": "**Do not** add a third naming site.",
    "sidebar-tag.cwd-alone.no-tag": "**do not** fall back to `discover_repo()`, which guesses",
    "sidebar-tag.fold-header.reads-bucket-not-member": "**Do not** feed a member's merged tag into a fold header:",
    # orgs layer.
    "orgs.defaults.no-org-aware-reader": "**Do not** add an org-aware reader, an `org_*` field, or a",
    "orgs.merge.one-level-deep": "**Do not** make it recursive.",
    "orgs.merge.never-persisted": "**Never persisted** — the config writers re-read",
    # Spawn and prompts.
    "spawn.context-flag.no-synthesis": "**Do not** teach the CLI to synthesize its own context.",
    "spawn.review-default.no-named-command": "**Do not** re-add a default naming any command",
    "spawn.adopt-grace.fails-open": "reads as old enough) — **do not** invert that test;",
    "spawn.coworker-pr.review-mode-only": "**Do not** add a nudge or authority grant keyed off the",
    "spawn.use-worktree-false.no-auto-spawn": "**Do not** let these repos reach any auto-spawn.",
    "spawn.unhide.single-gate-every-mode": "**Do not** move this into a per-mode branch, and **do not** key it on the worktree path.",
    "spawn.picker.parked-repos-selectable-and-not-deduped-away": "**Do not** make the picker filter them out, and **do not** delete",
    "spawn.ticket-prompt.reads-repo-block": "**`spawn.py`'s half is deferred",
    "spawn.plan-fallback.keeps-source-slot": "seeding the bare ref — **do not** drop the `source` slot.",
    "spawn.seed.no-enter-on-unconfirmed": "**Giving up presses no Enter.**",
    "spawn.seed.no-raise-attempt-count": "**Do not** answer a slow spawn by raising the attempt count.",
    "prompts.templates.all-resolve": "`tests/test_templates.py` asserts every template",
    "prompts.templates.no-inline-prose-or-conditionals": "**Do not** re-inline prompt prose into Python lists",
    "prompts.plan-gate.never-commit": "**Do not** teach it to commit that file",
    "prompts.plan-gate.never-daemon-read": "**Do not** promote it to a cache cell, a config field, or anything",
    "slack.no-mcp-preflight": "**Never** add a `claude mcp list` pre-flight gate",
    # gh: PR identity.
    "gh.pr-rank.not-number-alone": "**Do not** rank by number alone.",
    "gh.trunk-head.no-raw-headrefname": "**Do not** re-thread `headRefName` straight into a worktree branch.",
    "review-decision.single-construction-site": "**Do not** re-derive an approval at a renderer or gate.",
    # Sends: the idle gate, diff hand-over, broadcast, seed queue.
    "send.one-line.inside-the-funnel": "**Every message is collapsed to one line",
    "idle-gate.never-trust-needs-input": "**Never** simplify the gate to trust `Needs input`.",
    "idle-gate.reassert.no-second-authority": "**Do not** widen it to a second at-rest authority for those states.",
    "idle-gate.verdict.single-function": "**Do not** re-derive the verdict at a call site",
    "idle-pill.liveness.match-on-workspace-id": "**The liveness guard in the hook must compare",
    "diff-nudge.send.single-path": "**do not** give it a second send path.",
    "diff-nudge.scope.no-fan-out": "**Do not** generalise it into a fan-out.",
    "seed-queue.stale.no-eventual-delivery": '**Do not** lengthen this into "eventually it\'ll land".',
    "broadcast.send.reuse-nudge-gate": "**Do not** give it its own send path, idle check, or cache cell",
    "broadcast.repo.no-basename-alias": "**do not** accept the path basename as a second spelling",
    "orphan-nudge.removed.no-reinstate": '**Do not** re-add it, and **do not** answer "an abandoned worktree',
    # Nudge prefs.
    "nudge-prefs.key.requires-repo": "**Do not** add a call site that invents a key without a repo",
    "nudge.restamp-pref.scope-frozen": "**Do not** extend this to a cell the daemon derives.",
    "nudge.wake-signature.excludes-head-oid": "**Do not** fold `head_oid` into `wake_signature`",
    "nudge.snooze.no-time-based-until": "**Do not** give the snooze a time-based `until`.",
    "nudge.chain-snooze.converge-not-glyph": "**Do not** answer a half-snoozed chain by giving the snoozed row",
    "nudge-cli.split-chain.reuses-chain-tip": "so **do not** re-derive a chain in `nudge_cli.py`",
    # Teardown and cockpit diff.
    "teardown.unlanded.ownership-split-not-collapsed": "**Do not** collapse the two, and **do not** re-baseline",
    "teardown.close.never-raw-cmux": '**Never call `cmux("close-workspace", …)` raw.**',
    "diff.render.no-second-caller-params": "**Do not** add a `workspace=`/`keep_surface=` pair back for a second",
    "diff.source-flags.no-reimplemented-git": "**Do not** reimplement a git source in cockpit",
    "diff.viewer.no-second-renderer": "cockpit **must not** grow a second in-overlay renderer or a `delta`",
    "diff.resolution.no-configured-repo-required": "**Do not** route it through `close.py::_resolve_target`",
    "diff.comments.split-not-merged": "**Do not** re-merge them into one call.",
    # Capabilities and tickets config.
    "capabilities.tiers.must-exist": "**Every entry must name a tier cockpit actually HAS.**",
    "capabilities.gate.warn-never-exit": "**Do not** promote any of these to `sys.exit(2)`.",
    "capabilities.docs.no-verb-counts": "**Do not** write verb counts into prose here or there.",
    "tickets.schema.one-field-per-concept": "**Do not** re-split `dev_done`/`merge_done`/`token_env` per provider",
    "tickets.schema.no-legacy-alias": "**Do not** re-add an alias arg.",
    "tickets.schema.per-provider-not-flattened": "**do not** flatten the per-provider schemas into one merged dict.",
    "tickets.provider.no-sibling-field-guess": '**Do not** re-add a "guess the provider from a sibling field" rule.',
    "tickets.provider.no-name-ternaries": '**Do not** re-introduce `provider == "github" ? …` ternaries',
    "tickets.routing.narrow-reports-all-survivors": "**Do not** collapse this back to one key read off `candidates[0]`.",
    "tickets.jira.no-narrow-duplicate": "give it a `project` field or duplicate `find_repos_by_ticket_key`",
    "tickets.url.extract-not-verbatim": "**Do not** pass them through verbatim the way `slack`/`trello` mode",
    "tickets.credentials.envs-in-step-with-stripper": "**An unset credential warns at startup",
    "tickets.credentials.warning-no-ternary": "**do not** re-add a provider-name ternary, since the gate is",
    "tickets.no-preflight-any-provider": "**Do not** reintroduce a pre-flight for any provider.",
    "devdone.fetch.no-per-pr-fanout": "**Do not** drop back to a per-PR fetch fan-out.",
    # Ticket inbox.
    "ticket-inbox.grouping.two-axes-not-one": "**Do not** collapse them to one axis.",
    "ticket-inbox.fetch.empty-not-suspended": "suspended bucket keeps the payload it had. **Do not** re-key",
    "ticket-inbox.screen.no-narrow-repos-for-marker": "**Do not** call `narrow_repos` for a marker either",
    "ticket-inbox.markers.no-repo-column": "**Do not** answer this with a Repo column: key→repo is 1:1",
    "tickets-screen.columns.explicit-widths": "**Its columns take explicit widths, never `DataTable`'s auto-sizing.**",
    "ticket-routing.start-ticket.no-per-provider-waiver": "**Do not** re-add a per-provider waiver — Trello",
    "ticket-routing.start-ticket.no-cursor-row-default": "**Do not** replace any of this",
    # update_stale_branches.
    "update-stale.trigger.merge-state-not-base-distance": "**Do not** re-derive this from `base-distance`.",
    "update-stale.mechanism.no-local-rebase": "**Do not** replace this with a local rebase.",
    "update-stale.cas.expected-head-oid-mandatory": "the `--force-with-lease` equivalent. **Do not** drop it.",
    "update-stale.scope.no-widen-to-every-stale-pr": "**Do not** widen it to every stale PR.",
    "update-stale.dismissal-gate.no-remove": "has no approval to lose. **Do not** remove this gate.",
    "update-branch.dismisses-stale.two-sources": "**That verdict is TWO sources",
    "update-stale.two-sources.no-graphql-only-gate": "**Do not** gate on the GraphQL field alone.",
    "update-stale.ruleset-fail-closed.no-invert": "**Do not** invert this for symmetry.",
    "update-stale.resync.no-dirty-check-only": "**Do not** weaken `expected_head` to a dirty-check.",
    # Dev, release and the suite's own rules.
    "lint.ruff.no-uvx": "**Never lint/format with `uvx ruff`",
    "dry.gate.not-cycle-only": "**Do not** narrow the gate back to the cycle.",
    "dry.threading.single-path": "**Do not** re-hardcode that call site, and **do not** add a second dev-only suppression path beside it.",
    "dev-script.git-mutation.refusal": "**Do not** add a subcommand that mutates through git without a refusal beside it.",
    "skills-dir.footprint.distinct-directories": "**Do not** read the two as being about the same directory.",
    "skills-dir.rule-placement.judgment-only": "**Do not** put a rule here that a hook, a test, or a line in this file would hold better.",
    "release.tag-yml.keeps-credentials": "`tag.yml` is exempt from `artipacked`.",
    "release-please.commit-guard.pattern-sync": "so **do not** set `pull-request-title-pattern` without updating the guard.",
    "publish-yml.no-touch": "**Do not** touch `publish.yml` — check the pending-publisher claims first.",
    "suite.isolation.no-live-backend": "## The suite cannot reach the live machine",
    "suite.isolation.runtime-dir-needs-env-var": "isolating only `COCKPIT_HOME` **do not** cover the runtime dir",
    "tests.helpers.take-input-dont-fetch": "**An extracted helper takes its input; it does not fetch it.**",
    "tests.gates.verify-outcome-not-proxy": "must VERIFY THE OUTCOME",
    "e2e.followup-delivery.not-a-regression-test": "**Do not** promote it to one, and **do not** let a green run there read as proof the race is handled",
    "invariant-registry.covered-not-tested": "**Do not** read a covered id as a tested rule.",
    "invariant-registry.no-bulk-register": "**Do not** bulk-register.",
}

# A rule no test could ever assert against; not one that merely lacks a test
# yet. Every entry below constrains the shape of code a future change would
# add, or names a convention with nothing runnable to check.
JUDGMENT_ONLY: frozenset[str] = frozenset(
    {
        "docs.meta.never-do-not-lines-are-invariants",
        "inventory.identity.never-stored",
        "skills.no-redundant-gesture-skill",
        "header.repo-segment.no-repo-column-alternative",
        "tui.manual-nudge-key.not-reintroduced",
        "folds.review.never-persist-marker",
        "folds.mystery.not-closed",
        "stacks.derive.no-gh-view-no-persist",
        "sidebar-tag.naming.two-sites-only",
        "orgs.defaults.no-org-aware-reader",
        "prompts.templates.no-inline-prose-or-conditionals",
        "review-decision.single-construction-site",
        "diff-nudge.scope.no-fan-out",
        "diff.viewer.no-second-renderer",
        "capabilities.docs.no-verb-counts",
        "tickets.provider.no-name-ternaries",
        "lint.ruff.no-uvx",
        "skills-dir.footprint.distinct-directories",
        "skills-dir.rule-placement.judgment-only",
        "release-please.commit-guard.pattern-sync",
        "publish-yml.no-touch",
        "suite.isolation.runtime-dir-needs-env-var",
        "tests.helpers.take-input-dont-fetch",
        "tests.gates.verify-outcome-not-proxy",
        "e2e.followup-delivery.not-a-regression-test",
        "invariant-registry.covered-not-tested",
        "invariant-registry.no-bulk-register",
        # These five name a rejected design alternative — a test would pin the
        # current shape, not the reasoning that chose it.
        "header.announce-upgrade.no-version-check-widen",
        "header.menu.label-not-the-key",
        "hidden.h.single-key-three-meanings",
        "pills.pr-pill.coverage-narrower-accepted",
        "ticket-inbox.markers.no-repo-column",
    }
)
